/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import javax.swing.JOptionPane;
import Req_Res.Req_Res;
import java.io.IOException;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author kmish
 */
public class CancelTrain extends javax.swing.JFrame implements Serializable{
   
    private final Req_Res rr;
     private final String adminid;
    /**
     * Creates new form CancelTrain
     */
    public CancelTrain(Req_Res rr,String adminid) {
        initComponents();
        this.rr=rr;
        this.adminid=adminid;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txttrainnum = new javax.swing.JTextField();
        tncancel = new javax.swing.JButton();
        btnuncancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cancel and Uncancel Trains");

        jLabel2.setText("Train Number:");

        txttrainnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttrainnumKeyReleased(evt);
            }
        });

        tncancel.setText("Cancel Train");
        tncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tncancelActionPerformed(evt);
            }
        });

        btnuncancel.setText("Uncancel Train");
        btnuncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuncancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(txttrainnum, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(tncancel)
                        .addGap(164, 164, 164)
                        .addComponent(btnuncancel)))
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(242, 242, 242))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttrainnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tncancel)
                    .addComponent(btnuncancel))
                .addContainerGap(220, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tncancelActionPerformed
        // TODO add your handling code here:
    if(checkfields()){
        String tNum=txttrainnum.getText();
        if(tNum.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Enter Train Number");
        }
        else{
            try {
                //Req_Res res=new Req_Res();
                ViewTrain train=new ViewTrain();
                train.settrainNum(tNum);
                String Res=rr.cancelTrain(train);
                if(Res.equals("valid")){
                    System.out.println(Res+"2\n");
                    JOptionPane.showMessageDialog(this,"Train Successfully Cancelled");
                }
                else{
                    JOptionPane.showMessageDialog(this,Res);
                    System.out.println("\n"+Res);
                }
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(CancelTrain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    else{
        JOptionPane.showMessageDialog(this, "check if u have entered valic entries");
    }
    }//GEN-LAST:event_tncancelActionPerformed

    private void btnuncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuncancelActionPerformed
        // TODO add your handling code here:
    if(checkfields()){    
        String tNum=txttrainnum.getText();
        if(tNum.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Enter Train Number");
        }
        else{
            try {
                //Req_Res res=new Req_Res();
                ViewTrain train=new ViewTrain();
                train.settrainNum(tNum);
                String Res=rr.uncancelTrain(train);
                if(Res.equals("valid")){
                    System.out.println(Res+"3\n");
                    JOptionPane.showMessageDialog(this,"Train Successfully Uncancelled");
                }
                else{
                    JOptionPane.showMessageDialog(this,Res);
                    System.out.println("\n"+Res);
                }
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(CancelTrain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
    else{
        JOptionPane.showMessageDialog(this, "check if u have entered valic entries");
    }
    }//GEN-LAST:event_btnuncancelActionPerformed

    private void txttrainnumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttrainnumKeyReleased
        // TODO add your handling code here:
        
       String PATTERN="^[0-9]{2,5}$";
       Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txttrainnum.getText());
        if(!match.matches()){
           jLabel3.setText("invalid password");        }
       else{
            jLabel3.setText(null);
        }
    }//GEN-LAST:event_txttrainnumKeyReleased
   public boolean checkfields(){
        if (jLabel3.getText().equals("invalid")){
         return false;
        }
        else{
            return true;
       }
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnuncancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton tncancel;
    private javax.swing.JTextField txttrainnum;
    // End of variables declaration//GEN-END:variables
}
